language: node_js
node_js:
  - "10"

git:
  depth: 1

before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FA_TOKEN

before_script:
  - npm install -g gulp-cli

script: gulp


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: "tompaulus.com"
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  detect_encoding: true
  default_text_charset: 'utf-8'

