language: node_js
node_js:
  - "lts/*"

git:
  depth: 1

addons:
  apt:
    packages:
    - imagemagick
    - graphicsmagick

before_install:
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
  - aws codeartifact login --tool npm --repository fontawesome-pro --domain tompaulus --domain-owner 798453335285 --region us-east-1
  - npm install -g travis-ci-cloudfront-invalidation

before_script:
  - npm install -g gulp-cli

script: gulp

before_deploy:
  - mkdir upload
  - mv assets/ upload/
  - mv index.html upload

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "tompaulus.com"
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  detect_encoding: true
  default_text_charset: 'utf-8'
  local_dir: upload

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS -s $AWS_SECRET -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
